server:
  port: 17436
  compression:
    enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大上限
      max-file-size: 30MB
      # 单个请求的文件总大小上限
      max-request-size: 30MB

my-config:
  data-dir: data/
